# based on this article https://sergiodxa.com/articles/github-actions-npm-publish

name: Publish

on:
  release:
    types: [published] # this tells it to only publish when a new github release is made

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16 # current LTS
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --access public
        env:
          # you have to set this in the github repository settings, you get it from the npm package settings
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 
